### ISSUE TITLE
Dodać do wczytywanie danych dane o sąsiadach (nowy plik z danymi)

### ISSUE THREAD

**Issue by Gukson** [Gukson/PlagueInc#2]
W klasie wirus dodałem ArrayList neightboors - i tam trzeba dodać inne obiekty krajów które są sąsiadami danego

**Comment by 00200200** [comment]
Chyba lepszym rozwiazaniem, bedzie dodanie  kolumny neighbours w bazie danych i wtedy dodanie ich w neighbours?
